source 'https://github.com/CocoaPods/Specs.git'

# inhibit_all_warnings!
use_frameworks!

target 'SwiftExample' do
  pod 'SSZipArchive', :path => '..'
  pod 'mailcore2-ios'
  platform :ios, '8.0'
end
