source 'https://github.com/CocoaPods/Specs.git'

# inhibit_all_warnings!
use_frameworks!

abstract_target 'core' do

  pod 'SSZipArchive', :path => '..'

  target 'ObjectiveCExample' do
    pod 'mailcore2-ios'
    platform :ios, '8.0'
  end

  target 'ObjectiveCExampleTests_iOS' do
    pod 'mailcore2-ios'
    platform :ios, '8.0'
  end

  target 'ObjectiveCExampleTests_macOS' do
    pod 'mailcore2-osx'
    pod 'OpenSSL-Universal'
    platform :osx, '10.8'
  end

  target 'ObjectiveCExampleTests_tvOS' do
    platform :tvos, '9.0'
  end

end
